### PR TITLE
Mobile support

### PR DESCRIPTION
**Pull request by tradziej**

### CODE REVIEW

**Comment by anilmaurya** [comment]
@tradziej User may touch text without any intension of editing it.
 If we open input/text-box on first touch then it may be frustrating to user.
I think showing edit icon on first touch and than showing input/text-box on edit icon touch will be good.

@tothpeter What do you think ?

**Comment by sherpalabsio** [comment]
@anilmaurya 
Tough question, we use this addon in an app at my company, the app works on mobile as well, and it behaves pretty much the same, user taps on the text and then they can edit it, or not if the editing is disabled (usually there's an edit page, where the user tap it on purpose, and there's a show page where all the inplace addons are disabled). I believe we should keep things simple as possible and follow industrial standards here.

I asked around what my mobile developer friends are using and we agreed that the most common scenario reads as follow:
- There's a main switch checkbox (usually at the top of the page), and the user can use it to enable or disable editing globally on the page. Our addon is already capable of it, you can achieve it simple by using the `disabled` option.

So I think we should leave the behavior as it is now, considering the single tap, and displaying an edit button, it is configurable and flexible enough. (maximum adding an option to prevent the activate event to fire when the user clicks on the text, so only the edit button will trigger it)

@tradziej Your commit says "Do not show edit icon/button on mobile" but it only ads an extra event listener.  I bet you experienced that the addon does not clickable out of the box on mobile, at least in safari I'm sure. Does it solve this problem?

**Comment by tradziej** [comment]
@tothpeter Yes, that was a reason.

I know we could use CSS workaround: https://github.com/tradziej/ember-inplace-edit/commit/8a1d8499376128d007e1abaa667fdcea2a6819cf
but then it's not focusing on iOS devices.

Probably it stopped working after this change: https://github.com/anilmaurya/ember-inplace-edit/commit/d7680868b749370dc018a55cfe7adba08a5a1987

Could you look at it?

**Comment by sherpalabsio** [comment]
@tradziej Safari is a bit stingy on mobile devices when it comes to `focus()`ing textboxes. You should invoke `focus()` from inside the the click event handler synchronously to make it happen, but we have to wait the rendering hereö to finish, so it won't work pragmatically. But I've just tested out: if you add `autofocus="true"` to the input and textarea, it will work like charm on mobile as well. Thanks for drawing our attention to it. I will add it to the plugin as soon as we could agree on this pull request.

@anilmaurya I've just realized the addon works on 2 steps on mobile as you described above, and this pull request would shorten it into 1 step. Well, I think we could follow this direction, here are my reasons:
- In all of our apps in my company, we rule the addon's disabled property globally on the page level, so on the edit pages where the user expects to edit the content, everything is editable the fastest and easiest way: single click on it and boom, just like when you are editing your LinkedIn profile. On the contrary on the show pages the addon is disabled, so it only displays the text.
- There are a few guidelines they suggest: if the users have to click more then 3 times to reach what they want, that could make them inpatient. So we should keep this path as short as possible.

What do you think?

**Comment by anilmaurya** [comment]
@tothpeter Ok, Lets move in direction of single click edit.

**Comment by sherpalabsio** [comment]
@tradziej Thanks for your contribution :heart:

**Pull request merged**
